# Generated by Django 5.2.5 on 2025-09-25 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['visit_date']},
        ),
        migrations.AlterField(
            model_name='visit',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.coffeeshop'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.student'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(fields=('student', 'shop', 'visit_date'), name='unique_visit_date'),
        ),
    ]
