# Generated by Django 5.2.5 on 2025-12-04 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_review_name_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='visit',
        ),
    ]
