# Generated by Django 5.2.5 on 2025-12-04 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_review_name_remove_review_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.visit'),
        ),
    ]
